# Usage:
#  - `targetdir: /full/path/to/files/to/aggregate [specify full single directory]
#  -  (optional) `outputdir: /directory/to/drop/files` [specify output directory] 

# wage levels are impacts in mins/worker/day * population * income (365 * (labor_share = 0.6) / (250 days * 60 mins * 6 hours * elasticity = 0.5 )

# outputdir: if not specified will drop outputs in targetdir
outputdir: /project/cil/gcp/outputs/labor/impacts-corpsepose/single/single-interacted-test
#writedir: /project/cil/home_dirs/maiqi/repos/labor-code-release-2020/aggregation_interacted_single
weighting: population 
aggregated-unit: "mins/worker/day"
levels-unit: "mins/day"
infix: pop