outputdir: outputs/labor/impacts-woodwork/combined_uninteracted_splines_27_37_39_by_risk_empshare_noFE_YearlyAverageDay
# Levels are impacts in mins/worker/day * population * income (365 * (labor_share = 0.6) / (250 days * 60 mins * 6 hours * elasticity = 0.5 )
# targetdir: /shares/gcp/outputs/labor/impacts-woodwork/combined_uninteracted_splines_27_37_39_by_risk_empshare_noFE_YearlyAverageDay/median/rcp85/surrogate_GFDL-ESM2G_01/low/SSP4/
levels-weighting: population * 0.00487 / population 
aggregate-weighting-numerator: population * income * 0.00487
aggregate-weighting-denominator: population * income
only-variables: ["rebased","response","response22","clip"]
rcp: rcp85
ssp: SSP4
gcm: surrogate_GFDL-ESM2G_01
iam: low
infix: gdp