outputdir: outputs/labor/impacts-woodwork/mc_correct_rebasing_for_integration
# Levels are impacts in mins/worker/day * population * income (365 * (labor_share = 0.6) / (250 days * 60 mins * 6 hours * elasticity = 0.5 )
levels-weighting: population * 0.00487 / population 
aggregate-weighting-numerator: population * income * 0.00487
aggregate-weighting-denominator: population * income
infix: gdp
