cd /global/scratch/liruixue/repos

sbatch labor-code-release-2020/3_projection/1_run_projections/mc_correct_rebasing/brc_sbatch_savio1_low.sh
sbatch labor-code-release-2020/3_projection/1_run_projections/mc_correct_rebasing/brc_sbatch_savio1big_low.sh
sbatch labor-code-release-2020/3_projection/1_run_projections/mc_correct_rebasing/brc_sbatch_savio2_low.sh
sbatch labor-code-release-2020/3_projection/1_run_projections/mc_correct_rebasing/brc_sbatch_savio2big_low.sh
sbatch labor-code-release-2020/3_projection/1_run_projections/mc_correct_rebasing/brc_sbatch_savio2big_normal.sh
sbatch labor-code-release-2020/3_projection/1_run_projections/mc_correct_rebasing/brc_sbatch_savio3_low.sh
sbatch labor-code-release-2020/3_projection/1_run_projections/mc_correct_rebasing/brc_sbatch_savio3_normal.sh
sbatch labor-code-release-2020/3_projection/1_run_projections/mc_correct_rebasing/brc_sbatch_savio3big_low.sh
