mode: writecalcs
outputdir: /shares/gcp/outputs/labor/impacts-woodwork/hi_1factor_lo_unint_mixed_model_plankpose
do_historical: true
do_farmers: true
only-models: [ "CCSM4" ]
only-iam: "high"
only-ssp: "SSP3"
only-rcp: "rcp85"
singledir: combined_mixed_splines_27_37_39_by_risk_empshare_noFE_YearlyAverageDay
climcovar:
    class: mean
    length: 30
econcovar:
   class: mean
   length: 30

timerate: day
climate: [ tasmax, tasmax_rcspline, tas, tas-poly-2, tas-poly-3, tas-poly-4  ]
models:
  - csvvs: social/parameters/labor/post_replication/hi_1factor_lo_unint_mixed_model_splines_empshare_noFE.csvv
    covariates: [ loggdppc, climtas, climtas-poly-2, climtas-poly-3, climtas-poly-4 ]
    knots: [ 27, 37, 39 ]
    description: labor productivity
    specifications:
        minlost_lo:
            csvv-subset: [0, 2]  # Which columns in CSVV? (0-indexing!)
            csvv-reunit:
                - variable: outcome
                  new-unit: minutes worked by individual
            description: low-risk labor productivity
            indepunit: C
            depenunit: minutes worked by individual  
            description: low-risk labor productivity
            functionalform: cubicspline
            prefix: tasmax_rcspline
            variable: tasmax
        minlost_hi:
            csvv-subset: [2, 6]
            csvv-reunit:
                - variable: outcome
                  new-unit: minutes worked by individual
            indepunit: C
            depenunit: minutes worked by individual
            description: high-risk labor productivity
            functionalform: cubicspline
            prefix: tasmax_rcspline
            variable: tasmax
            clipping: plankpose
            clip-model: minlost_lo
        riskshare_hi:
            csvv-subset: [6, 12]
            csvv-reunit:
                - variable: outcome
                  new-unit: unitless
            indepunit: C
            depenunit: unitless
            description: share of high-risk labor
            functionalform: coefficients
            variables:
                - 1 [scalar]
    calculation:
        - YearlyAverageDay:
            model: minlost_lo
        - Reword:
            name: lowriskimpacts
        - YearlyAverageDay:
            model: minlost_hi
        - Reword:
            name: highriskimpacts
        - FractionSum:
            - highriskimpacts
            - Clip:
                - YearlyAverageDay:
                    model: riskshare_hi
                - 0.046444122  # Historical clip min value
                - 0.99408281   # Historical clip max value
            - lowriskimpacts
        - Rebase
        - KeepOnly:
            - rebased
            - clip
            - highriskimpacts
            - lowriskimpacts