results-root: /project/cil/gcp/outputs/labor/impacts-woodwork/montecarlo/uninteracted_main_model
output-dir: /project/cil/gcp/outputs/labor/impacts-woodwork/montecarlo/test
file-organize: [ssp, region]
do-montecarlo: yes
only-rcp: rcp85
only-models: all
only-iam: low
column: rebased
output-format: valuescsv
ignore-missing: no

