outputdir: /project/cil/gcp/outputs/labor/impacts-woodwork/median/uninteracted_main_model_agnonag_27_28_41-global
weighting: population 
aggregated-unit: "mins/worker/day"
levels-unit: "mins/day"
infix: pop
