outputdir: outputs/labor/impacts-woodwork/labor_mc_re-rebased
targetdir: /shares/gcp/outputs/labor/impacts-woodwork/labor_mc_re-rebased/batch0/rcp85/CCSM4/high/SSP3
# Levels are ioutputs/labor/impacts-woodwork/labor_mc_re-rebasedmpacts in mins/worker/day * population * income (365 * (labor_share = 0.6) / (250 days * 60 mins * 6 hours * elasticity = 0.5 )
levels-weighting: income * 0.00487
aggregate-weighting-numerator: income * 0.00487
aggregate-weighting-denominator: sum-to-1
infix: gdppc
