outputdir: /global/scratch/liruixue/outputs/labor/impacts-woodwork/labor_mc_re-rebased
# Levels are impacts in mins/worker/day * population * income (365 * (labor_share = 0.6) / (250 days * 60 mins * 6 hours * elasticity = 0.5 )
levels-weighting: population * 0.00487 / population 
aggregate-weighting-numerator: population * income * 0.00487
aggregate-weighting-denominator: population * income
infix: gdp
batch: batch0
